### ISSUE TITLE
We investigate remote container debuging

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/interface_rs485#10]
## Expected Behavior
 - We should be able to connect to interface RS485 while remote debuging

## Current Behavior
 - Unable to access remote interface

## Possible Solution
 - ?

## Environment Used
- Project version : 1.0 
- docker version : 19.03.8, build afacb8
- docker-compose version : 1.25.5, build 8a1c60f

**Comment by 0x72D0** [comment]
I think I don't understand the problematic quite well... you want to do remote debugging with the RS485 protocol or you want to be able to debug the RS485 node in the docker container?

**Comment by supertoto29** [comment]
This issue has been resolved by adding this line in the docker file
`RUN usermod -a -G dialout ${SONIA_USER}`
These 2 lines in the devcontainer.json
In the runArgs `"--privileged",`
In the mounts `"source=/dev,target=/dev,type=bind"`
