### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by marcantoinecouture** [sonia-auv/interface_rs485#5]
## Expected Behaviour
This project is used to communicate through RS485, using ROS messages to read and write on the bus. The department who own this project is the software team since it uses ROS.

## Current Behaviour
The repo name makes the electrical team owner of the project

## Possible Solution
Rename the repo correctly

## Comments
Thank you

**Comment by marcantoinecouture** [comment]
`interface_rs485` was the previous name and I think we should keep it. It's a ROS "interface" between ROS messages and the RS485 communication protocol.

**Comment by gauthiermartin** [comment]
@coumarc9 Repository has been renamed ! Please confirm and close this issue

**Comment by marcantoinecouture** [comment]
The previous name was `interface_rs485` with lower cases. Do we want this name?

**Comment by marcantoinecouture** [comment]
My mistake, the name had upper cases, but all the code uses `rs` instead of `RS` and all other repo name's are in lower-cases. What do you think?

**Comment by gauthiermartin** [comment]
For backward compatibilities issue i think we should leave it to interface_RS485

**Comment by gauthiermartin** [comment]
Closing this issue !
